using OgmaLibrary.Application.Reader;
using OgmaLibrary.Domain;

namespace OgmaLibrary.Reader.Annotations;

/// <summary>
/// Manages durable bookmarks for the reader (FR-READ-007, NFR-OGMA-008).
/// Emits <see cref="AnnotationEvent"/> values after successful writes.
/// </summary>
public sealed class BookmarkService : IBookmarkService, IDisposable
{
    private readonly IBookmarkRepository _repository;
    private readonly IAnnotationEventPublisher _events;
    private readonly IAnnotationReadModel _readModel;
    private readonly AnnotationReadModel? _ownedReadModel;

    /// <summary>
    /// Initializes a new instance of <see cref="BookmarkService"/>.
    /// </summary>
    /// <param name="repository">The bookmark persistence repository.</param>
    /// <param name="events">The shared annotation event publisher.</param>
    public BookmarkService(IBookmarkRepository repository, IAnnotationEventPublisher? events = null)
    {
        ArgumentNullException.ThrowIfNull(repository);
        _repository = repository;
        if (events is null)
        {
            var readModel = new AnnotationReadModel();
            _events = readModel;
            _readModel = readModel;
            _ownedReadModel = readModel;
        }
        else
        {
            _events = events;
            _readModel = events as IAnnotationReadModel
                ?? throw new ArgumentException(
                    "Annotation event publisher must also expose the read model stream.",
                    nameof(events));
        }
    }

    /// <summary>Observable stream of bookmark lifecycle events.</summary>
    public IObservable<AnnotationEvent> Events => _readModel.Events;

    /// <inheritdoc />
    public async Task<Bookmark> CreateAsync(
        string bookId,
        int pageIndex,
        string? label,
        CancellationToken cancellationToken)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(bookId);

        var bookmark = new Bookmark
        {
            Id = 0L, // Auto-generated by the DB.
            BookId = bookId,
            PageIndex = pageIndex,
            Label = string.IsNullOrWhiteSpace(label) ? null : label.Trim(),
            CreatedUtc = DateTimeOffset.UtcNow,
        };

        Bookmark saved = await _repository
            .CreateAsync(bookmark, cancellationToken)
            .ConfigureAwait(false);

        _events.Publish(new AnnotationEvent.BookmarkCreated(bookId, saved));
        return saved;
    }

    /// <inheritdoc />
    public async Task RenameAsync(
        long bookmarkId,
        string newLabel,
        CancellationToken cancellationToken)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(newLabel);
        Bookmark? existing = await _repository
            .FindAsync(bookmarkId, cancellationToken)
            .ConfigureAwait(false);
        if (existing is null)
        {
            return;
        }

        await _repository.RenameAsync(bookmarkId, newLabel, cancellationToken).ConfigureAwait(false);

        var updated = new Bookmark
        {
            Id = existing.Id,
            BookId = existing.BookId,
            PageIndex = existing.PageIndex,
            Label = newLabel,
            CreatedUtc = existing.CreatedUtc,
        };
        _events.Publish(new AnnotationEvent.BookmarkUpdated(updated.BookId, updated));
    }

    /// <inheritdoc />
    public async Task DeleteAsync(long bookmarkId, CancellationToken cancellationToken)
    {
        Bookmark? existing = await _repository
            .FindAsync(bookmarkId, cancellationToken)
            .ConfigureAwait(false);

        await _repository.DeleteAsync(bookmarkId, cancellationToken).ConfigureAwait(false);

        if (existing is not null)
        {
            _events.Publish(new AnnotationEvent.BookmarkDeleted(existing.BookId, bookmarkId));
        }
    }

    /// <inheritdoc />
    public Task<IReadOnlyList<Bookmark>> GetForBookAsync(
        string bookId,
        CancellationToken cancellationToken)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(bookId);
        return _repository.ListForBookAsync(bookId, cancellationToken);
    }

    /// <inheritdoc />
    public void Dispose() => _ownedReadModel?.Dispose();
}
