using OgmaLibrary.Application;

namespace OgmaLibrary.App.Icons;

/// <summary>
/// A resolved icon: the avares:// path for use as an SVG image source and the
/// localized accessible label for <c>AutomationProperties.Name</c>.
/// </summary>
/// <param name="AvaresPath">The <c>avares://OgmaLibrary.App/Assets/icons/…</c> path.</param>
/// <param name="AccessibleLabel">The localized string for the icon's accessible label.</param>
public sealed record IconEntry(string AvaresPath, string AccessibleLabel);

/// <summary>
/// Registry mapping each Phase 03 <c>icon_key</c> to its SVG asset path and localized
/// accessible label. The SVG assets live at
/// <c>Assets/icons/&lt;category&gt;/&lt;key&gt;.svg</c>; placeholders are generated by
/// <c>scripts/New-PlaceholderIcons.ps1</c> and will be replaced by premium Flaticon SVGs
/// via <c>scripts/Import-Icons.ps1</c>.
/// </summary>
public static class IconCatalog
{
    private const string AssemblyPrefix = "avares://OgmaLibrary.App/Assets/icons/";

    /// <summary>
    /// Maps each icon key to its category-relative asset path (without the avares:// prefix).
    /// The key is the <c>icon_key</c> string from the phase-03 icon manifest.
    /// </summary>
    private static readonly IReadOnlyDictionary<string, string> AssetPaths =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            // Category: app
            ["ic_app_logo"] = "app/ic_app_logo.svg",
            ["ic_settings"] = "app/ic_settings.svg",
            ["ic_keyboard_shortcut"] = "app/ic_keyboard_shortcut.svg",
            ["ic_close"] = "app/ic_close.svg",
            ["ic_search"] = "app/ic_search.svg",

            // Category: library
            ["ic_lib_scan"] = "library/ic_lib_scan.svg",
            ["ic_lib_folder_open"] = "library/ic_lib_folder_open.svg",
            ["ic_lib_health"] = "library/ic_lib_health.svg",
            ["ic_lib_preferences"] = "library/ic_lib_preferences.svg",

            // Category: catalogue
            ["ic_cat_view_grid"] = "catalogue/ic_cat_view_grid.svg",
            ["ic_cat_view_list"] = "catalogue/ic_cat_view_list.svg",
            ["ic_cat_view_shelf3d"] = "catalogue/ic_cat_view_shelf3d.svg",
            ["ic_cat_view_directory"] = "catalogue/ic_cat_view_directory.svg",
            ["ic_cat_shelf"] = "catalogue/ic_cat_shelf.svg",
            ["ic_cat_shelf_new"] = "catalogue/ic_cat_shelf_new.svg",
            ["ic_cat_filter"] = "catalogue/ic_cat_filter.svg",
            ["ic_cat_sort"] = "catalogue/ic_cat_sort.svg",

            // Category: reader
            ["ic_read_open"] = "reader/ic_read_open.svg",
            ["ic_read_bookmark"] = "reader/ic_read_bookmark.svg",
            ["ic_read_zoom_in"] = "reader/ic_read_zoom_in.svg",
            ["ic_read_zoom_out"] = "reader/ic_read_zoom_out.svg",
            ["ic_read_fullscreen"] = "reader/ic_read_fullscreen.svg",

            // Category: search
            ["ic_search_metadata"] = "search/ic_search_metadata.svg",
            ["ic_search_fulltext"] = "search/ic_search_fulltext.svg",

            // Category: ai
            ["ic_ai_advisor"] = "ai/ic_ai_advisor.svg",
            ["ic_ai_privacy"] = "ai/ic_ai_privacy.svg",
            ["ic_ai_disable"] = "ai/ic_ai_disable.svg",

            // Category: settings
            ["ic_set_appearance"] = "settings/ic_set_appearance.svg",
            ["ic_set_language"] = "settings/ic_set_language.svg",
            ["ic_set_updates"] = "settings/ic_set_updates.svg",
            ["ic_set_about"] = "settings/ic_set_about.svg",

            // Category: status
            ["ic_status_available"] = "status/ic_status_available.svg",
            ["ic_status_unavailable"] = "status/ic_status_unavailable.svg",
            ["ic_status_loading"] = "status/ic_status_loading.svg",
        };

    /// <summary>
    /// Returns the full <c>avares://</c> path for the given icon key, or <c>null</c> if the
    /// key is not registered.
    /// </summary>
    /// <param name="key">The icon key (e.g. <c>"ic_app_logo"</c>).</param>
    /// <returns>The <c>avares://OgmaLibrary.App/Assets/icons/…</c> URI string.</returns>
    public static string? GetAvaresPath(string key)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(key);
        return AssetPaths.TryGetValue(key, out string? rel) ? AssemblyPrefix + rel : null;
    }

    /// <summary>
    /// Resolves an icon to its avares:// path and localized accessible label.
    /// Returns <c>null</c> if the key is not registered.
    /// </summary>
    /// <param name="key">The icon key (e.g. <c>"ic_settings"</c>).</param>
    /// <param name="localization">The active localization service.</param>
    /// <returns>
    /// An <see cref="IconEntry"/> with the asset path and accessible label, or <c>null</c>.
    /// </returns>
    public static IconEntry? Resolve(string key, ILocalizationService localization)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(key);
        ArgumentNullException.ThrowIfNull(localization);

        if (!AssetPaths.TryGetValue(key, out string? rel))
        {
            return null;
        }

        string path = AssemblyPrefix + rel;
        string labelKey = $"Icon.{key}.Label";
        string label = localization[labelKey];
        return new IconEntry(path, label);
    }

    /// <summary>
    /// Returns all 34 registered icon keys.
    /// </summary>
    public static IEnumerable<string> AllKeys => AssetPaths.Keys;
}
