// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OgmaLibrary.Infrastructure.Catalogue;

#nullable disable

namespace OgmaLibrary.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogueDbContext))]
    [Migration("20260601104115_Phase11EmbeddingSchema")]
    partial class Phase11EmbeddingSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.AiQueryHistoryRow", b =>
                {
                    b.Property<long>("QueryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CostEstimate")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("ModelId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("PrivacyTier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("QueryText")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestPayloadHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseSummary")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TokensIn")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TokensOut")
                        .HasColumnType("INTEGER");

                    b.HasKey("QueryId");

                    b.HasIndex("CreatedUtc")
                        .HasDatabaseName("IX_AiQueryHistory_CreatedUtc");

                    b.ToTable("AiQueryHistory", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.AnnotationBodyRow", b =>
                {
                    b.Property<string>("AnnotationId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteText")
                        .HasMaxLength(65536)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuoteText")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<string>("RectJson")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("AnnotationId");

                    b.ToTable("AnnotationBodies", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.AnnotationLayerRow", b =>
                {
                    b.Property<string>("LayerId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("BookId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("#FFD700");

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("LayerId");

                    b.HasIndex("BookId")
                        .HasDatabaseName("IX_AnnotationLayers_BookId");

                    b.ToTable("AnnotationLayers", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.AnnotationRow", b =>
                {
                    b.Property<string>("AnnotationId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("BookId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorKey")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Page")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("AnnotationId");

                    b.HasIndex("BookId", "Page")
                        .HasDatabaseName("IX_Annotations_BookId_Page");

                    b.ToTable("Annotations", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.AnnotationV2Row", b =>
                {
                    b.Property<string>("AnnotationId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("BookId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorKey")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LayerId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteText")
                        .HasMaxLength(65536)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuoteText")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegionsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("AnnotationId");

                    b.HasIndex("LayerId")
                        .HasDatabaseName("IX_AnnotationsV2_LayerId");

                    b.HasIndex("BookId", "LayerId")
                        .HasDatabaseName("IX_AnnotationsV2_BookId_LayerId");

                    b.ToTable("AnnotationsV2", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.AuditEventRow", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActorId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("AfterJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLocalOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_AuditEvents_Timestamp");

                    b.HasIndex("EntityId", "EntityType")
                        .HasDatabaseName("IX_AuditEvents_EntityId_EntityType");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.AuthorRow", b =>
                {
                    b.Property<long>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SortName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("AuthorId");

                    b.HasIndex("NormalizedName")
                        .HasDatabaseName("IX_Authors_NormalizedName");

                    b.ToTable("Authors", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.BookAuthorRow", b =>
                {
                    b.Property<string>("BookId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<long>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Role")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("BookId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("BookAuthors", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.BookFileRow", b =>
                {
                    b.Property<long>("BookFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<int>("FileStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.HasKey("BookFileId");

                    b.HasIndex("RelativePath")
                        .HasDatabaseName("IX_BookFiles_RelativePath");

                    b.HasIndex("BookId", "FileStatus")
                        .HasDatabaseName("IX_BookFiles_BookId_FileStatus");

                    b.ToTable("BookFiles", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.BookMetadataFieldRow", b =>
                {
                    b.Property<long>("FieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOverridden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Source")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("SourceTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.HasKey("FieldId");

                    b.HasIndex("BookId", "FieldName", "Source")
                        .HasDatabaseName("IX_BookMetadataFields_BookId_FieldName_Source");

                    b.ToTable("BookMetadataFields", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.BookRow", b =>
                {
                    b.Property<string>("BookId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("Doi")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long?>("EditionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmbeddingStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("IndexStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("IsbnNormalized")
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<long?>("MtimeTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PdfFingerprint")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<double>("QualityScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelativePath")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256Hash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("BookId");

                    b.HasIndex("EditionId");

                    b.HasIndex("EmbeddingStatus")
                        .HasDatabaseName("IX_Books_EmbeddingStatus");

                    b.HasIndex("IndexStatus")
                        .HasDatabaseName("IX_Books_IndexStatus");

                    b.HasIndex("IsbnNormalized")
                        .HasDatabaseName("IX_Books_IsbnNormalized");

                    b.HasIndex("RelativePath")
                        .HasDatabaseName("IX_Books_RelativePath");

                    b.HasIndex("Sha256Hash")
                        .HasDatabaseName("IX_Books_Sha256Hash");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Books_Status");

                    b.HasIndex("Title", "IsbnNormalized")
                        .HasDatabaseName("IX_Books_Title_IsbnNormalized");

                    b.ToTable("Books", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.BookmarkRow", b =>
                {
                    b.Property<long>("BookmarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Page")
                        .HasColumnType("INTEGER");

                    b.HasKey("BookmarkId");

                    b.HasIndex("BookId", "Page")
                        .HasDatabaseName("IX_Bookmarks_BookId_Page");

                    b.ToTable("Bookmarks", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.EditionRow", b =>
                {
                    b.Property<long>("EditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Publisher")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long>("WorkId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EditionId");

                    b.HasIndex("WorkId");

                    b.ToTable("Editions", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.EmbeddingVectorRow", b =>
                {
                    b.Property<long>("VectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChunkId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DimensionCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("GeneratedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("VectorBlob")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("VectorId");

                    b.HasIndex("ChunkId", "ModelName", "ModelVersion")
                        .IsUnique()
                        .HasDatabaseName("UX_EmbeddingVectors_ChunkId_ModelName_ModelVersion");

                    b.ToTable("EmbeddingVectors", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.ExtractedPageRow", b =>
                {
                    b.Property<long>("ExtractedPageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<string>("ExtractionMethod")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExtractionQuality")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(2);

                    b.Property<DateTimeOffset?>("ExtractionUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("PageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TextContent")
                        .HasColumnType("TEXT");

                    b.Property<int>("WordCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("ExtractedPageId");

                    b.HasIndex("BookId", "ContentHash")
                        .HasDatabaseName("IX_ExtractedPages_BookId_ContentHash");

                    b.HasIndex("BookId", "PageNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_ExtractedPages_BookId_PageNumber");

                    b.ToTable("ExtractedPages", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.JobRow", b =>
                {
                    b.Property<long>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .HasMaxLength(65536)
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset?>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("JobId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UQ_Jobs_IdempotencyKey");

                    b.HasIndex("Status", "JobType")
                        .HasDatabaseName("IX_Jobs_Status_JobType");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.MetadataLookupRow", b =>
                {
                    b.Property<long>("LookupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Applied")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("BookId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestIsbn")
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("LookupId");

                    b.HasIndex("BookId", "Provider", "Timestamp")
                        .HasDatabaseName("IX_MetadataLookups_BookId_Provider_Timestamp");

                    b.ToTable("MetadataLookups", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.ReadingMemoryRow", b =>
                {
                    b.Property<string>("BookId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Disposition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyInsight")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenQuestions")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenedBecause")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("BookId");

                    b.ToTable("ReadingMemory", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.ReadingProgressRow", b =>
                {
                    b.Property<string>("BookId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<double>("CompletionPct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<int>("CurrentPage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset?>("LastReadUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("ScrollOffsetPx")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalPagesRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("BookId");

                    b.ToTable("ReadingProgress", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.SearchChunkRow", b =>
                {
                    b.Property<long>("ChunkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChunkText")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExtractedPageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("TokenCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("ChunkId");

                    b.HasIndex("ExtractedPageId");

                    b.HasIndex("BookId", "ChunkIndex")
                        .HasDatabaseName("IX_SearchChunks_BookId_ChunkIndex");

                    b.HasIndex("BookId", "Source")
                        .HasDatabaseName("IX_SearchChunks_BookId_Source");

                    b.ToTable("SearchChunks", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.ShelfBookRow", b =>
                {
                    b.Property<string>("ShelfId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("BookId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AddedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("ShelfId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("ShelfBooks", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.ShelfRow", b =>
                {
                    b.Property<string>("ShelfId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Query")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int>("ShelfType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("ShelfId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Shelves_Name");

                    b.ToTable("Shelves", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.WorkRow", b =>
                {
                    b.Property<long>("WorkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CanonicalAuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalTitle")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("WorkId");

                    b.ToTable("Works", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.AnnotationBodyRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.AnnotationRow", "Annotation")
                        .WithOne("Body")
                        .HasForeignKey("OgmaLibrary.Infrastructure.Catalogue.Entities.AnnotationBodyRow", "AnnotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Annotation");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.AnnotationLayerRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.BookRow", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.AnnotationRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.BookRow", "Book")
                        .WithMany("Annotations")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.AnnotationV2Row", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.BookRow", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.AnnotationLayerRow", "Layer")
                        .WithMany("Annotations")
                        .HasForeignKey("LayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Book");

                    b.Navigation("Layer");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.BookAuthorRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.AuthorRow", "Author")
                        .WithMany("BookAuthors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.BookRow", "Book")
                        .WithMany("BookAuthors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.BookFileRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.BookRow", "Book")
                        .WithMany("BookFiles")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.BookMetadataFieldRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.BookRow", "Book")
                        .WithMany("MetadataFields")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.BookRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.EditionRow", "Edition")
                        .WithMany("Books")
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Edition");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.BookmarkRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.BookRow", "Book")
                        .WithMany("Bookmarks")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.EditionRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.WorkRow", "Work")
                        .WithMany("Editions")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Work");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.EmbeddingVectorRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.SearchChunkRow", "Chunk")
                        .WithMany("EmbeddingVectors")
                        .HasForeignKey("ChunkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chunk");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.ExtractedPageRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.BookRow", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.MetadataLookupRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.BookRow", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.ReadingMemoryRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.BookRow", "Book")
                        .WithOne("ReadingMemory")
                        .HasForeignKey("OgmaLibrary.Infrastructure.Catalogue.Entities.ReadingMemoryRow", "BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.ReadingProgressRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.BookRow", "Book")
                        .WithOne("ReadingProgress")
                        .HasForeignKey("OgmaLibrary.Infrastructure.Catalogue.Entities.ReadingProgressRow", "BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.SearchChunkRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.ExtractedPageRow", "ExtractedPage")
                        .WithMany("SearchChunks")
                        .HasForeignKey("ExtractedPageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ExtractedPage");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.ShelfBookRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.BookRow", "Book")
                        .WithMany("ShelfBooks")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.ShelfRow", "Shelf")
                        .WithMany("ShelfBooks")
                        .HasForeignKey("ShelfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Shelf");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.AnnotationLayerRow", b =>
                {
                    b.Navigation("Annotations");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.AnnotationRow", b =>
                {
                    b.Navigation("Body");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.AuthorRow", b =>
                {
                    b.Navigation("BookAuthors");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.BookRow", b =>
                {
                    b.Navigation("Annotations");

                    b.Navigation("BookAuthors");

                    b.Navigation("BookFiles");

                    b.Navigation("Bookmarks");

                    b.Navigation("MetadataFields");

                    b.Navigation("ReadingMemory");

                    b.Navigation("ReadingProgress");

                    b.Navigation("ShelfBooks");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.EditionRow", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.ExtractedPageRow", b =>
                {
                    b.Navigation("SearchChunks");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.SearchChunkRow", b =>
                {
                    b.Navigation("EmbeddingVectors");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.ShelfRow", b =>
                {
                    b.Navigation("ShelfBooks");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.WorkRow", b =>
                {
                    b.Navigation("Editions");
                });
#pragma warning restore 612, 618
        }
    }
}
