// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using OgmaLibrary.Infrastructure.Catalogue;

#nullable disable

namespace OgmaLibrary.Infrastructure.Persistence.Migrations;

/// <inheritdoc />
[DbContext(typeof(CatalogueDbContext))]
[Migration("20260904230000_Phase21AnnotationCoordinateVersion")]
partial class Phase21AnnotationCoordinateVersion
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        // The model snapshot is the authoritative current model. This migration
        // descriptor intentionally carries only the product-version marker; its
        // Up/Down operations are the complete expand/contract change.
        modelBuilder.HasAnnotation("ProductVersion", "10.0.9");
    }
}
