// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OgmaLibrary.Infrastructure.Catalogue;

#nullable disable

namespace OgmaLibrary.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogueDbContext))]
    partial class CatalogueDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.AiAuditEventRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("EstimatedCostUsd")
                        .HasColumnType("REAL");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PromptCacheTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("QueryHistoryEntryId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tier")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("IX_AiAuditEvents_OccurredAt");

                    b.HasIndex("QueryHistoryEntryId")
                        .HasDatabaseName("IX_AiAuditEvents_QueryHistoryEntryId");

                    b.ToTable("AiAuditEvents", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.AiConsentRecordRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tier")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Tier", "Provider", "Scope")
                        .HasDatabaseName("IX_AiConsentRecords_Tier_Provider_Scope");

                    b.ToTable("AiConsentRecords", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.AiQueryHistoryRow", b =>
                {
                    b.Property<long>("QueryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CostEstimate")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("HistoryId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("ModelId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("PrivacyTier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("QueryText")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<string>("QueryType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestPayloadHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseSummary")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TokensIn")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TokensOut")
                        .HasColumnType("INTEGER");

                    b.HasKey("QueryId");

                    b.HasIndex("CreatedUtc")
                        .HasDatabaseName("IX_AiQueryHistory_CreatedUtc");

                    b.HasIndex("HistoryId")
                        .IsUnique()
                        .HasDatabaseName("UX_AiQueryHistory_HistoryId");

                    b.ToTable("AiQueryHistory", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.AiUsageLedgerRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EstimatedCostUsd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0m);

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("QueryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("TokensUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_AiUsageLedger_Date");

                    b.HasIndex("ProfileId", "Date")
                        .IsUnique()
                        .HasDatabaseName("UX_AiUsageLedger_ProfileId_Date");

                    b.ToTable("AiUsageLedger", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.AnnotationBodyRow", b =>
                {
                    b.Property<string>("AnnotationId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteText")
                        .HasMaxLength(65536)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuoteText")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<string>("RectJson")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("AnnotationId");

                    b.ToTable("AnnotationBodies", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.AnnotationLayerRow", b =>
                {
                    b.Property<string>("LayerId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("BookId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("#FFD700");

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("LayerId");

                    b.HasIndex("BookId")
                        .HasDatabaseName("IX_AnnotationLayers_BookId");

                    b.ToTable("AnnotationLayers", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.AnnotationRow", b =>
                {
                    b.Property<string>("AnnotationId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("BookId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorKey")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Page")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("AnnotationId");

                    b.HasIndex("BookId", "Page")
                        .HasDatabaseName("IX_Annotations_BookId_Page");

                    b.ToTable("Annotations", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.AnnotationV2Row", b =>
                {
                    b.Property<string>("AnnotationId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("BookId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorKey")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LayerId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteText")
                        .HasMaxLength(65536)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuoteText")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegionsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("AnnotationId");

                    b.HasIndex("LayerId")
                        .HasDatabaseName("IX_AnnotationsV2_LayerId");

                    b.HasIndex("BookId", "LayerId")
                        .HasDatabaseName("IX_AnnotationsV2_BookId_LayerId");

                    b.ToTable("AnnotationsV2", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.AuditEventRow", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActorId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("AfterJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLocalOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_AuditEvents_Timestamp");

                    b.HasIndex("EntityId", "EntityType")
                        .HasDatabaseName("IX_AuditEvents_EntityId_EntityType");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.AuthorRow", b =>
                {
                    b.Property<long>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SortName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("AuthorId");

                    b.HasIndex("NormalizedName")
                        .HasDatabaseName("IX_Authors_NormalizedName");

                    b.ToTable("Authors", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.BibliographicIdentifierRow", b =>
                {
                    b.Property<long>("BibliographicIdentifierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EditionId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<int>("IdentifierKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedValue")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerScope")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.HasKey("BibliographicIdentifierId");

                    b.HasIndex("EditionId")
                        .HasDatabaseName("IX_BibliographicIdentifiers_EditionId");

                    b.HasIndex("WorkId")
                        .HasDatabaseName("IX_BibliographicIdentifiers_WorkId");

                    b.HasIndex("OwnerScope", "Source", "IdentifierKind", "NormalizedValue")
                        .IsUnique()
                        .HasDatabaseName("UX_BibliographicIdentifiers_ScopedValue");

                    b.ToTable("BibliographicIdentifiers", null, t =>
                        {
                            t.HasCheckConstraint("CK_BibliographicIdentifiers_Kind", "IdentifierKind BETWEEN 0 AND 4");

                            t.HasCheckConstraint("CK_BibliographicIdentifiers_Owner", "(OwnerScope = 0 AND WorkId IS NOT NULL AND EditionId IS NULL) OR (OwnerScope = 1 AND EditionId IS NOT NULL AND WorkId IS NULL)");

                            t.HasCheckConstraint("CK_BibliographicIdentifiers_Scope", "OwnerScope IN (0, 1)");
                        });
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.BookAuthorRow", b =>
                {
                    b.Property<string>("BookId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<long>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Role")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("BookId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("BookAuthors", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.BookFileRow", b =>
                {
                    b.Property<long>("BookFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<int>("FileStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.HasKey("BookFileId");

                    b.HasIndex("RelativePath")
                        .HasDatabaseName("IX_BookFiles_RelativePath");

                    b.HasIndex("BookId", "FileStatus")
                        .HasDatabaseName("IX_BookFiles_BookId_FileStatus");

                    b.ToTable("BookFiles", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.BookMetadataFieldRow", b =>
                {
                    b.Property<long>("FieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOverridden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Source")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("SourceTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.HasKey("FieldId");

                    b.HasIndex("FieldName", "Value")
                        .HasDatabaseName("IX_BookMetadataFields_FieldName_Value");

                    b.HasIndex("BookId", "FieldName", "Source")
                        .HasDatabaseName("IX_BookMetadataFields_BookId_FieldName_Source");

                    b.ToTable("BookMetadataFields", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.BookRow", b =>
                {
                    b.Property<string>("BookId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("Doi")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long?>("EditionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmbeddingStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("IndexStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsOcrDerived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPasswordProtected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("IsbnNormalized")
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<long?>("MtimeTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PdfFingerprint")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<double>("QualityScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelativePath")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256Hash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("BookId");

                    b.HasIndex("EditionId");

                    b.HasIndex("EmbeddingStatus")
                        .HasDatabaseName("IX_Books_EmbeddingStatus");

                    b.HasIndex("IndexStatus")
                        .HasDatabaseName("IX_Books_IndexStatus");

                    b.HasIndex("IsOcrDerived")
                        .HasDatabaseName("IX_Books_IsOcrDerived");

                    b.HasIndex("IsPasswordProtected")
                        .HasDatabaseName("IX_Books_IsPasswordProtected");

                    b.HasIndex("IsbnNormalized")
                        .HasDatabaseName("IX_Books_IsbnNormalized");

                    b.HasIndex("RelativePath")
                        .HasDatabaseName("IX_Books_RelativePath");

                    b.HasIndex("Sha256Hash")
                        .HasDatabaseName("IX_Books_Sha256Hash");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Books_Status");

                    b.HasIndex("Status", "Year")
                        .HasDatabaseName("IX_Books_Status_Year");

                    b.HasIndex("Title", "IsbnNormalized")
                        .HasDatabaseName("IX_Books_Title_IsbnNormalized");

                    b.ToTable("Books", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.BookmarkRow", b =>
                {
                    b.Property<long>("BookmarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Page")
                        .HasColumnType("INTEGER");

                    b.HasKey("BookmarkId");

                    b.HasIndex("BookId", "Page")
                        .HasDatabaseName("IX_Bookmarks_BookId_Page");

                    b.ToTable("Bookmarks", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.CanonicalEditionRow", b =>
                {
                    b.Property<string>("EditionId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Publisher")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("ResolutionState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.HasKey("EditionId");

                    b.HasIndex("WorkId", "ResolutionState")
                        .HasDatabaseName("IX_CanonicalEditions_Work_State");

                    b.ToTable("CanonicalEditions", null, t =>
                        {
                            t.HasCheckConstraint("CK_CanonicalEditions_Id", "length(EditionId) = 26");

                            t.HasCheckConstraint("CK_CanonicalEditions_State", "ResolutionState BETWEEN 0 AND 3");

                            t.HasCheckConstraint("CK_CanonicalEditions_WorkId", "length(WorkId) = 26");
                        });
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.CanonicalWorkRow", b =>
                {
                    b.Property<string>("WorkId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalTitle")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResolutionState")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkId");

                    b.HasIndex("ResolutionState")
                        .HasDatabaseName("IX_CanonicalWorks_State");

                    b.ToTable("CanonicalWorks", null, t =>
                        {
                            t.HasCheckConstraint("CK_CanonicalWorks_Id", "length(WorkId) = 26");

                            t.HasCheckConstraint("CK_CanonicalWorks_State", "ResolutionState BETWEEN 0 AND 3");
                        });
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.CatalogueItemOccurrenceRow", b =>
                {
                    b.Property<string>("CatalogueItemId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileOccurrenceId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.HasKey("CatalogueItemId", "FileOccurrenceId");

                    b.HasIndex("FileOccurrenceId")
                        .HasDatabaseName("IX_CatalogueItemOccurrences_OccurrenceId");

                    b.ToTable("CatalogueItemOccurrences", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.CatalogueItemRow", b =>
                {
                    b.Property<string>("CatalogueItemId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EditionId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredOccurrenceId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.HasKey("CatalogueItemId");

                    b.HasIndex("PreferredOccurrenceId");

                    b.HasIndex("EditionId", "WorkId");

                    b.HasIndex("WorkId", "EditionId")
                        .HasDatabaseName("IX_CatalogueItems_Work_Edition");

                    b.ToTable("CatalogueItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_CatalogueItems_EditionId", "length(EditionId) = 26");

                            t.HasCheckConstraint("CK_CatalogueItems_Id", "length(CatalogueItemId) = 26");

                            t.HasCheckConstraint("CK_CatalogueItems_PreferredOccurrenceId", "PreferredOccurrenceId IS NULL OR length(PreferredOccurrenceId) = 26");

                            t.HasCheckConstraint("CK_CatalogueItems_WorkId", "length(WorkId) = 26");
                        });
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.ContentAssetRow", b =>
                {
                    b.Property<string>("ContentAssetId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("FingerprintVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sha256Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("ContentAssetId");

                    b.HasIndex("Sha256Hash", "FingerprintVersion")
                        .IsUnique()
                        .HasDatabaseName("UX_ContentAssets_Hash_Version");

                    b.ToTable("ContentAssets", null, t =>
                        {
                            t.HasCheckConstraint("CK_ContentAssets_FingerprintVersion", "FingerprintVersion > 0");

                            t.HasCheckConstraint("CK_ContentAssets_Id", "length(ContentAssetId) = 26");

                            t.HasCheckConstraint("CK_ContentAssets_Sha256", "length(Sha256Hash) = 64 AND Sha256Hash NOT GLOB '*[^0-9a-f]*'");

                            t.HasCheckConstraint("CK_ContentAssets_Size", "SizeBytes IS NULL OR SizeBytes > 0");

                            t.HasCheckConstraint("CK_ContentAssets_Verification", "VerificationStatus IN (0, 1)");
                        });
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.EditionContentAssetRow", b =>
                {
                    b.Property<string>("EditionId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentAssetId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.HasKey("EditionId", "ContentAssetId");

                    b.HasIndex("ContentAssetId")
                        .HasDatabaseName("IX_EditionContentAssets_AssetId");

                    b.ToTable("EditionContentAssets", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.EditionRow", b =>
                {
                    b.Property<long>("EditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Publisher")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long>("WorkId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EditionId");

                    b.HasIndex("WorkId");

                    b.ToTable("Editions", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.EmbeddingVectorRow", b =>
                {
                    b.Property<long>("VectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChunkId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DimensionCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("GeneratedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("VectorBlob")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("VectorId");

                    b.HasIndex("ChunkId", "ModelName", "ModelVersion")
                        .IsUnique()
                        .HasDatabaseName("UX_EmbeddingVectors_ChunkId_ModelName_ModelVersion");

                    b.ToTable("EmbeddingVectors", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.EnrolledProfileRow", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EnrolledUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnrollmentToken")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EnrollmentTokenExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RevokedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("ProfileId");

                    b.HasIndex("EnrollmentToken")
                        .IsUnique()
                        .HasDatabaseName("UX_EnrolledProfiles_EnrollmentToken");

                    b.HasIndex("Role", "RevokedUtc")
                        .HasDatabaseName("IX_EnrolledProfiles_Role_RevokedUtc");

                    b.ToTable("EnrolledProfiles", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.ExtractedPageRow", b =>
                {
                    b.Property<long>("ExtractedPageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<string>("ExtractionMethod")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExtractionQuality")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(2);

                    b.Property<DateTimeOffset?>("ExtractionUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("PageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Extraction");

                    b.Property<string>("TextContent")
                        .HasColumnType("TEXT");

                    b.Property<int>("WordCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("ExtractedPageId");

                    b.HasIndex("BookId", "ContentHash")
                        .HasDatabaseName("IX_ExtractedPages_BookId_ContentHash");

                    b.HasIndex("BookId", "PageNumber")
                        .HasDatabaseName("IX_ExtractedPages_BookId_PageNumber");

                    b.HasIndex("BookId", "Source", "PageNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_ExtractedPages_BookId_Source_PageNumber");

                    b.ToTable("ExtractedPages", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.FileOccurrenceRow", b =>
                {
                    b.Property<string>("FileOccurrenceId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<int>("AvailabilityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentAssetId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LibraryRootId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ModifiedUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedRelativePath")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("PdfFingerprint")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("FileOccurrenceId");

                    b.HasIndex("ContentAssetId", "AvailabilityStatus")
                        .HasDatabaseName("IX_FileOccurrences_Asset_Availability");

                    b.HasIndex("LibraryRootId", "NormalizedRelativePath")
                        .IsUnique()
                        .HasDatabaseName("UX_FileOccurrences_Root_NormalizedPath");

                    b.ToTable("FileOccurrences", null, t =>
                        {
                            t.HasCheckConstraint("CK_FileOccurrences_AssetId", "ContentAssetId IS NULL OR length(ContentAssetId) = 26");

                            t.HasCheckConstraint("CK_FileOccurrences_Availability", "AvailabilityStatus IN (0, 1)");

                            t.HasCheckConstraint("CK_FileOccurrences_Id", "length(FileOccurrenceId) = 26");

                            t.HasCheckConstraint("CK_FileOccurrences_RootId", "length(LibraryRootId) = 26");

                            t.HasCheckConstraint("CK_FileOccurrences_Size", "SizeBytes IS NULL OR SizeBytes >= 0");
                        });
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.HostClientSessionRow", b =>
                {
                    b.Property<string>("TokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("IssuedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RevokedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("TokenHash");

                    b.HasIndex("RevokedUtc")
                        .HasDatabaseName("IX_HostClientSessions_RevokedUtc");

                    b.HasIndex("ClientId", "ExpiresUtc")
                        .HasDatabaseName("IX_HostClientSessions_ClientId_ExpiresUtc");

                    b.ToTable("HostClientSessions", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.HostModeSettingsRow", b =>
                {
                    b.Property<string>("SettingsId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("ContentMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("SettingsId");

                    b.ToTable("HostModeSettings", (string)null);

                    b.HasData(
                        new
                        {
                            SettingsId = "default",
                            ContentMode = 0,
                            DisplayName = "Ogma Library",
                            IsEnabled = false,
                            Port = 7473,
                            UpdatedUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.IdentityDecisionRow", b =>
                {
                    b.Property<string>("IdentityDecisionId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateOccurrenceId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Disposition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EvidenceTier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Relationship")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubjectOccurrenceId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.HasKey("IdentityDecisionId");

                    b.HasIndex("CandidateOccurrenceId");

                    b.HasIndex("SubjectOccurrenceId", "CandidateOccurrenceId", "PolicyVersion")
                        .HasDatabaseName("IX_IdentityDecisions_Pair_Version");

                    b.ToTable("IdentityDecisions", null, t =>
                        {
                            t.HasCheckConstraint("CK_IdentityDecisions_Confidence", "Confidence BETWEEN 0.0 AND 1.0");

                            t.HasCheckConstraint("CK_IdentityDecisions_Disposition", "Disposition IN (0, 1)");

                            t.HasCheckConstraint("CK_IdentityDecisions_DistinctOccurrences", "SubjectOccurrenceId <> CandidateOccurrenceId");

                            t.HasCheckConstraint("CK_IdentityDecisions_Id", "length(IdentityDecisionId) = 26");

                            t.HasCheckConstraint("CK_IdentityDecisions_PolicyVersion", "PolicyVersion > 0");

                            t.HasCheckConstraint("CK_IdentityDecisions_Relationship", "Relationship BETWEEN 0 AND 4");

                            t.HasCheckConstraint("CK_IdentityDecisions_Tier", "EvidenceTier BETWEEN 0 AND 4");
                        });
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.JobRow", b =>
                {
                    b.Property<long>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .HasMaxLength(65536)
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset?>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("JobId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UQ_Jobs_IdempotencyKey");

                    b.HasIndex("Status", "JobType")
                        .HasDatabaseName("IX_Jobs_Status_JobType");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.LegacyIdentityAliasRow", b =>
                {
                    b.Property<string>("LegacyBookId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CatalogueItemId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EditionId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<int>("MigrationVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.HasKey("LegacyBookId");

                    b.HasIndex("CatalogueItemId")
                        .IsUnique()
                        .HasDatabaseName("UX_LegacyIdentityAliases_CatalogueItemId");

                    b.HasIndex("EditionId", "WorkId");

                    b.ToTable("LegacyIdentityAliases", null, t =>
                        {
                            t.HasCheckConstraint("CK_LegacyIdentityAliases_CatalogueItemId", "length(CatalogueItemId) = 26");

                            t.HasCheckConstraint("CK_LegacyIdentityAliases_EditionId", "length(EditionId) = 26");

                            t.HasCheckConstraint("CK_LegacyIdentityAliases_Version", "MigrationVersion > 0");

                            t.HasCheckConstraint("CK_LegacyIdentityAliases_WorkId", "length(WorkId) = 26");
                        });
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.LibraryPublishSettingsRow", b =>
                {
                    b.Property<string>("LibraryRootId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("AiTier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("LibraryRootId");

                    b.HasIndex("IsPublished")
                        .HasDatabaseName("IX_LibraryPublishSettings_IsPublished");

                    b.HasIndex("SourcePath")
                        .IsUnique()
                        .HasDatabaseName("UX_LibraryPublishSettings_SourcePath");

                    b.ToTable("LibraryPublishSettings", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.LibraryRootRow", b =>
                {
                    b.Property<string>("LibraryRootId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompatibilityRoot")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RootStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("LibraryRootId");

                    b.ToTable("LibraryRoots", null, t =>
                        {
                            t.HasCheckConstraint("CK_LibraryRoots_Id", "length(LibraryRootId) = 26");

                            t.HasCheckConstraint("CK_LibraryRoots_Status", "RootStatus BETWEEN 0 AND 3");
                        });
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.MetadataLookupRow", b =>
                {
                    b.Property<long>("LookupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Applied")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("BookId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestIsbn")
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("LookupId");

                    b.HasIndex("BookId", "Provider", "Timestamp")
                        .HasDatabaseName("IX_MetadataLookups_BookId_Provider_Timestamp");

                    b.ToTable("MetadataLookups", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.ReadingMemoryRow", b =>
                {
                    b.Property<string>("BookId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Disposition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyInsight")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenQuestions")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenedBecause")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("BookId");

                    b.ToTable("ReadingMemory", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.ReadingProgressRow", b =>
                {
                    b.Property<string>("BookId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<double>("CompletionPct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<int>("CurrentPage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset?>("LastReadUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("ScrollOffsetPx")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalPagesRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("BookId");

                    b.ToTable("ReadingProgress", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.SchoolAiEntitlementRow", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("ClassDailyTokenBudget")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(500000);

                    b.Property<int>("DailyTokenBudget")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(10000);

                    b.Property<int>("RateLimitQueriesPerMin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(5);

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("ProfileId");

                    b.ToTable("SchoolAiEntitlements", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.SearchChunkRow", b =>
                {
                    b.Property<long>("ChunkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChunkText")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExtractedPageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("TokenCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("ChunkId");

                    b.HasIndex("ExtractedPageId");

                    b.HasIndex("BookId", "ChunkIndex")
                        .HasDatabaseName("IX_SearchChunks_BookId_ChunkIndex");

                    b.HasIndex("BookId", "Source")
                        .HasDatabaseName("IX_SearchChunks_BookId_Source");

                    b.ToTable("SearchChunks", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.SharedShelfBookRow", b =>
                {
                    b.Property<string>("ShelfId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BookId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AddedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("ShelfId", "BookId");

                    b.HasIndex("BookId")
                        .HasDatabaseName("IX_SharedShelfBooks_BookId");

                    b.ToTable("SharedShelfBooks", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.SharedShelfRow", b =>
                {
                    b.Property<string>("ShelfId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupIdsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Visibility")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("ShelfId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_SharedShelves_Name");

                    b.HasIndex("Visibility", "IsDeleted")
                        .HasDatabaseName("IX_SharedShelves_Visibility_IsDeleted");

                    b.ToTable("SharedShelves", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.ShelfBookRow", b =>
                {
                    b.Property<string>("ShelfId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("BookId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AddedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("ShelfId", "BookId");

                    b.HasIndex("BookId");

                    b.HasIndex("ShelfId", "BookId")
                        .HasDatabaseName("IX_ShelfBooks_ShelfId_BookId");

                    b.ToTable("ShelfBooks", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.ShelfRow", b =>
                {
                    b.Property<string>("ShelfId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Query")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int>("ShelfType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("ShelfId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Shelves_Name");

                    b.ToTable("Shelves", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.WorkRow", b =>
                {
                    b.Property<long>("WorkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CanonicalAuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalTitle")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("WorkId");

                    b.ToTable("Works", (string)null);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.AnnotationBodyRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.AnnotationRow", "Annotation")
                        .WithOne("Body")
                        .HasForeignKey("OgmaLibrary.Infrastructure.Catalogue.Entities.AnnotationBodyRow", "AnnotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Annotation");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.AnnotationLayerRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.BookRow", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.AnnotationRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.BookRow", "Book")
                        .WithMany("Annotations")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.AnnotationV2Row", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.BookRow", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.AnnotationLayerRow", "Layer")
                        .WithMany("Annotations")
                        .HasForeignKey("LayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Book");

                    b.Navigation("Layer");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.BibliographicIdentifierRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.CanonicalEditionRow", null)
                        .WithMany()
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.CanonicalWorkRow", null)
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.BookAuthorRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.AuthorRow", "Author")
                        .WithMany("BookAuthors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.BookRow", "Book")
                        .WithMany("BookAuthors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.BookFileRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.BookRow", "Book")
                        .WithMany("BookFiles")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.BookMetadataFieldRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.BookRow", "Book")
                        .WithMany("MetadataFields")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.BookRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.EditionRow", "Edition")
                        .WithMany("Books")
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Edition");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.BookmarkRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.BookRow", "Book")
                        .WithMany("Bookmarks")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.CanonicalEditionRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.CanonicalWorkRow", null)
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.CatalogueItemOccurrenceRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.CatalogueItemRow", null)
                        .WithMany()
                        .HasForeignKey("CatalogueItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.FileOccurrenceRow", null)
                        .WithMany()
                        .HasForeignKey("FileOccurrenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.CatalogueItemRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.FileOccurrenceRow", null)
                        .WithMany()
                        .HasForeignKey("PreferredOccurrenceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.CanonicalEditionRow", null)
                        .WithMany()
                        .HasForeignKey("EditionId", "WorkId")
                        .HasPrincipalKey("EditionId", "WorkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.EditionContentAssetRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.ContentAssetRow", null)
                        .WithMany()
                        .HasForeignKey("ContentAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.CanonicalEditionRow", null)
                        .WithMany()
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.EditionRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.WorkRow", "Work")
                        .WithMany("Editions")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Work");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.EmbeddingVectorRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.SearchChunkRow", "Chunk")
                        .WithMany("EmbeddingVectors")
                        .HasForeignKey("ChunkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chunk");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.ExtractedPageRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.BookRow", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.FileOccurrenceRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.ContentAssetRow", null)
                        .WithMany()
                        .HasForeignKey("ContentAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.LibraryRootRow", null)
                        .WithMany()
                        .HasForeignKey("LibraryRootId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.IdentityDecisionRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.FileOccurrenceRow", null)
                        .WithMany()
                        .HasForeignKey("CandidateOccurrenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.FileOccurrenceRow", null)
                        .WithMany()
                        .HasForeignKey("SubjectOccurrenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.LegacyIdentityAliasRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.CatalogueItemRow", null)
                        .WithMany()
                        .HasForeignKey("CatalogueItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.CanonicalEditionRow", null)
                        .WithMany()
                        .HasForeignKey("EditionId", "WorkId")
                        .HasPrincipalKey("EditionId", "WorkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.MetadataLookupRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.BookRow", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.ReadingMemoryRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.BookRow", "Book")
                        .WithOne("ReadingMemory")
                        .HasForeignKey("OgmaLibrary.Infrastructure.Catalogue.Entities.ReadingMemoryRow", "BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.ReadingProgressRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.BookRow", "Book")
                        .WithOne("ReadingProgress")
                        .HasForeignKey("OgmaLibrary.Infrastructure.Catalogue.Entities.ReadingProgressRow", "BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.SearchChunkRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.ExtractedPageRow", "ExtractedPage")
                        .WithMany("SearchChunks")
                        .HasForeignKey("ExtractedPageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ExtractedPage");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.SharedShelfBookRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.BookRow", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.SharedShelfRow", "Shelf")
                        .WithMany("Books")
                        .HasForeignKey("ShelfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Shelf");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.ShelfBookRow", b =>
                {
                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.BookRow", "Book")
                        .WithMany("ShelfBooks")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OgmaLibrary.Infrastructure.Catalogue.Entities.ShelfRow", "Shelf")
                        .WithMany("ShelfBooks")
                        .HasForeignKey("ShelfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Shelf");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.AnnotationLayerRow", b =>
                {
                    b.Navigation("Annotations");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.AnnotationRow", b =>
                {
                    b.Navigation("Body");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.AuthorRow", b =>
                {
                    b.Navigation("BookAuthors");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.BookRow", b =>
                {
                    b.Navigation("Annotations");

                    b.Navigation("BookAuthors");

                    b.Navigation("BookFiles");

                    b.Navigation("Bookmarks");

                    b.Navigation("MetadataFields");

                    b.Navigation("ReadingMemory");

                    b.Navigation("ReadingProgress");

                    b.Navigation("ShelfBooks");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.EditionRow", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.ExtractedPageRow", b =>
                {
                    b.Navigation("SearchChunks");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.SearchChunkRow", b =>
                {
                    b.Navigation("EmbeddingVectors");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.SharedShelfRow", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.ShelfRow", b =>
                {
                    b.Navigation("ShelfBooks");
                });

            modelBuilder.Entity("OgmaLibrary.Infrastructure.Catalogue.Entities.WorkRow", b =>
                {
                    b.Navigation("Editions");
                });
#pragma warning restore 612, 618
        }
    }
}
