<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <AvaloniaVersion>11.3.17</AvaloniaVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\OgmaLibrary.App\OgmaLibrary.App.csproj" />
    <ProjectReference Include="..\OgmaLibrary.Tests\OgmaLibrary.Tests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
    <PackageReference Include="Avalonia.Headless.XUnit" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Skia" Version="$(AvaloniaVersion)" />
  </ItemGroup>

</Project>
