using System.Globalization;
using OgmaLibrary.Application;

namespace OgmaLibrary.Infrastructure.Localization;

/// <summary>
/// A simple in-memory <see cref="ILocalizationService"/> carrying the MVP English and
/// French resource sets. It establishes the localization pattern for Phase 02; the
/// production resource format (satellite <c>.resx</c> vs structured JSON) is selected
/// by a dedicated ADR and migrated in Phase 03 without changing this contract.
/// </summary>
public sealed class InMemoryLocalizationService : ILocalizationService
{
    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["MainWindow.Title"] = "Ogma Library",
        ["MainWindow.Tagline"] = "Your personal PDF library — beautifully managed, intelligently advised.",
        ["MainWindow.EmptyState.Heading"] = "Your library will appear here",
        ["MainWindow.EmptyState.Body"] = "Choose a folder of PDFs to begin. Ogma will scan it, recognise your books, and let you browse them as covers and spines.",
        ["MainWindow.Action.ChooseFolder"] = "Choose library folder",
        ["MainWindow.Action.OpenPdf"] = "Open PDF",
        ["MainWindow.Status.Skeleton"] = "Skeleton build — Phase 02",

        // Phase 03 icon accessible labels (en)
        ["Icon.ic_app_logo.Label"] = "Ogma Library",
        ["Icon.ic_settings.Label"] = "Settings",
        ["Icon.ic_keyboard_shortcut.Label"] = "Keyboard shortcut",
        ["Icon.ic_close.Label"] = "Close",
        ["Icon.ic_search.Label"] = "Search",
        ["Icon.ic_lib_scan.Label"] = "Scan library",
        ["Icon.ic_lib_folder_open.Label"] = "Open library folder",
        ["Icon.ic_lib_health.Label"] = "Library health",
        ["Icon.ic_lib_preferences.Label"] = "Library preferences",
        ["Icon.ic_cat_view_grid.Label"] = "Grid view",
        ["Icon.ic_cat_view_list.Label"] = "List view",
        ["Icon.ic_cat_view_shelf3d.Label"] = "3D shelf view",
        ["Icon.ic_cat_view_directory.Label"] = "Directory view",
        ["Icon.ic_cat_shelf.Label"] = "Shelf",
        ["Icon.ic_cat_shelf_new.Label"] = "New shelf",
        ["Icon.ic_cat_filter.Label"] = "Filter",
        ["Icon.ic_cat_sort.Label"] = "Sort",
        ["Icon.ic_read_open.Label"] = "Open book",
        ["Icon.ic_read_bookmark.Label"] = "Bookmark",
        ["Icon.ic_read_zoom_in.Label"] = "Zoom in",
        ["Icon.ic_read_zoom_out.Label"] = "Zoom out",
        ["Icon.ic_read_fullscreen.Label"] = "Full screen",
        ["Icon.ic_search_metadata.Label"] = "Search books",
        ["Icon.ic_search_fulltext.Label"] = "Full-text search",
        ["Icon.ic_ai_advisor.Label"] = "AI advisor",
        ["Icon.ic_ai_privacy.Label"] = "AI privacy settings",
        ["Icon.ic_ai_disable.Label"] = "Disable AI",
        ["Icon.ic_set_appearance.Label"] = "Appearance",
        ["Icon.ic_set_language.Label"] = "Language",
        ["Icon.ic_set_updates.Label"] = "Updates",
        ["Icon.ic_set_about.Label"] = "About",
        ["Icon.ic_status_available.Label"] = "Available",
        ["Icon.ic_status_unavailable.Label"] = "Unavailable",
        ["Icon.ic_status_loading.Label"] = "Loading",

        // Phase 05 — Scan progress and status strings (en)
        ["Scan.Phase.Idle"] = "Ready",
        ["Scan.Phase.Discovering"] = "Discovering files…",
        ["Scan.Phase.Processing"] = "Processing…",
        ["Scan.Phase.GeneratingAssets"] = "Generating thumbnails…",
        ["Scan.Phase.Complete"] = "Scan complete",
        ["Scan.Phase.PartialFailure"] = "Scan complete — some files failed",
        ["Scan.Phase.Cancelled"] = "Scan cancelled",
        ["Scan.Status.Scanned"] = "Scanned {0} books",
        ["Scan.Button.Cancel"] = "Cancel",
        ["Scan.Progress.Files"] = "{0} / {1} files",
        ["Scan.Progress.Failed"] = "{0} failed",
        ["MainWindow.FolderPicker.Opening"] = "Opening folder picker...",
        ["MainWindow.FolderPicker.ScanStarting"] = "Library folder selected. Starting scan...",
        ["MainWindow.FolderPicker.Unavailable"] = "Folder picker is unavailable in this window.",
        ["MainWindow.FolderPicker.NotConfigured"] = "Library folder picker is not configured.",
        ["MainWindow.FolderPicker.FailedFormat"] = "Folder picker failed: {0}",
        ["MainWindow.PdfPicker.Opening"] = "Opening PDF picker...",
        ["MainWindow.PdfPicker.Registering"] = "Registering selected PDF...",
        ["MainWindow.PdfPicker.Opened"] = "PDF opened in reader.",
        ["MainWindow.PdfPicker.Unavailable"] = "PDF picker is unavailable in this window.",
        ["MainWindow.PdfPicker.NotConfigured"] = "Direct PDF opening is not configured.",
        ["MainWindow.PdfPicker.FailedFormat"] = "PDF open failed: {0}",
        ["MainWindow.PdfPicker.PdfFiles"] = "PDF documents",
        ["MainWindow.Status.Ready"] = "Ready — choose a library folder to begin",

        // Phase 06 — Catalogue browsing strings (en)
        ["Catalogue.ViewToggle.Grid"] = "Grid view",
        ["Catalogue.ViewToggle.List"] = "List view",
        ["Catalogue.ViewToggle.Directory"] = "Directory view",
        ["Catalogue.ViewToggle.Shelf3D"] = "3D shelf (coming in Phase 14)",
        ["Catalogue.Filter.ClearAll"] = "Clear all filters",
        ["Catalogue.Filter.Title"] = "Filter by title",
        ["Catalogue.Filter.Author"] = "Filter by author",
        ["Catalogue.Filter.Status"] = "Filter by status",
        ["Catalogue.Filter.Rating"] = "Filter by rating",
        ["Catalogue.Filter.Availability"] = "Filter by availability",
        ["Catalogue.Sort.Title"] = "Sort by title",
        ["Catalogue.Sort.Author"] = "Sort by author",
        ["Catalogue.Sort.Year"] = "Sort by year",
        ["Catalogue.Sort.Rating"] = "Sort by rating",
        ["Catalogue.Sort.Status"] = "Sort by status",
        ["Catalogue.Sort.Ascending"] = "Ascending",
        ["Catalogue.Sort.Descending"] = "Descending",
        ["Catalogue.Shelf.New"] = "New shelf",
        ["Catalogue.Shelf.Rename"] = "Rename shelf",
        ["Catalogue.Shelf.Delete"] = "Delete shelf",
        ["Catalogue.BookDetail.Read"] = "Read",
        ["Catalogue.BookDetail.Enrich"] = "Enrich",
        ["Catalogue.BookDetail.Close"] = "Close",
        ["Catalogue.BookDetail.EnrichTooltip"] = "Look up metadata from Google Books and Open Library",
        ["Catalogue.BookDetail.Enriching"] = "Looking up book metadata...",
        ["Catalogue.BookDetail.EnrichComplete"] = "Metadata enrichment complete.",
        ["Catalogue.BookDetail.EnrichUnavailable"] = "Metadata enrichment is unavailable.",
        ["Catalogue.BookDetail.EnrichUnknownError"] = "Unknown error",
        ["Catalogue.BookDetail.EnrichFailedFormat"] = "Metadata enrichment failed: {0}",
        ["Catalogue.BookDetail.ReadingMemory"] = "Reading memory",
        ["Catalogue.BookDetail.ReadingMemoryKeyInsight"] = "Key insight",
        ["Catalogue.BookDetail.ReadingMemoryDisposition"] = "Disposition",
        ["Catalogue.BookDetail.ReadingMemoryDispositionFormat"] = "{0}/5",
        ["Catalogue.BookDetail.ReadingMemoryEmpty"] = "Not recorded",
        ["Catalogue.Empty.NoResults"] = "No books match the current filters",
        ["Catalogue.Empty.NoShelfBooks"] = "This shelf has no books yet",
        ["Reader.Phase08Placeholder"] = "PDF reader coming in Phase 08",

        // Phase 08 — Reader strings (en)
        ["Reader.Navigation.FirstPage"] = "First page",
        ["Reader.Navigation.PreviousPage"] = "Previous page",
        ["Reader.Navigation.NextPage"] = "Next page",
        ["Reader.Navigation.LastPage"] = "Last page",
        ["Reader.Navigation.GoBack"] = "Go back",
        ["Reader.Navigation.GoForward"] = "Go forward",
        ["Reader.Navigation.JumpToPage"] = "Jump to page",
        ["Reader.Navigation.PageOf"] = "Page {0} of {1}",
        ["Reader.Navigation.InvalidPage"] = "Page must be between 1 and {0}",
        ["Reader.Zoom.FitWidth"] = "Fit width",
        ["Reader.Zoom.FitPage"] = "Fit page",
        ["Reader.Zoom.Fixed"] = "{0}%",
        ["Reader.Zoom.ZoomIn"] = "Zoom in",
        ["Reader.Zoom.ZoomOut"] = "Zoom out",
        ["Reader.Display.SinglePage"] = "Single page",
        ["Reader.Display.TwoPage"] = "Two pages",
        ["Reader.Display.Continuous"] = "Continuous scroll",
        ["Reader.FullScreen.Enter"] = "Enter full screen",
        ["Reader.FullScreen.Exit"] = "Exit full screen",
        ["Reader.Search.Placeholder"] = "Search in document…",
        ["Reader.Search.NoResults"] = "No matches found",
        ["Reader.Search.MatchCount"] = "{0} match(es)",
        ["Reader.Search.NoTextLayer"] = "No text layer — OCR available in V1",
        ["Reader.Error.FileNotFound"] = "The PDF file could not be found.",
        ["Reader.Error.RenderFailed"] = "Page could not be rendered.",
        ["Reader.Panel.Title"] = "Reader",

        // Phase 09 — Annotations, Bookmarks & Reading Memory (en)
        ["Annotation.Highlight.Create"] = "Highlight",
        ["Annotation.Highlight.Color"] = "Choose highlight color",
        ["Annotation.Highlight.LayerColor"] = "Layer color",
        ["Annotation.Note.Create"] = "Add note",
        ["Annotation.Note.Anchor"] = "Note",
        ["Annotation.Note.Edit"] = "Edit note",
        ["Annotation.Note.Editor"] = "Note",
        ["Annotation.Note.Saved"] = "Note saved",
        ["Annotation.Delete"] = "Delete annotation",
        ["Annotation.Panel"] = "Annotations",
        ["Annotation.Saved"] = "Annotation saved",
        ["Annotation.Deleted"] = "Annotation deleted",
        ["Annotation.SelectionQuoteFormat"] = "Selection on page {0}",
        ["Annotation.SampleQuoteFormat"] = "Highlight on page {0}",
        ["Annotation.SampleNoteFormat"] = "Note on page {0}",
        ["Annotation.AccessibleLabelWithLayerFormat"] = "{0} - {1} - {2}",
        ["Annotation.AccessibleLabelWithoutLayerFormat"] = "{0} - {1}",
        ["Annotation.Delete.Confirm"] = "Delete",
        ["Annotation.Delete.Cancel"] = "Cancel",
        ["Annotation.Delete.Confirmation"] = "Delete this {0}?",
        ["Bookmark.Add"] = "Add bookmark",
        ["Bookmark.Remove"] = "Remove bookmark",
        ["Bookmark.Panel"] = "Bookmarks",
        ["Bookmark.Item"] = "Bookmark",
        ["Bookmark.Rename"] = "Rename bookmark",
        ["Bookmark.Renamed"] = "Bookmark renamed",
        ["Bookmark.Saved"] = "Bookmark saved",
        ["Bookmark.Removed"] = "Bookmark removed",
        ["Bookmark.DefaultLabelFormat"] = "Page {0}",
        ["Bookmark.Panel.AccessibleFormat"] = "{0} ({1})",
        ["Layer.Panel"] = "Annotation layers",
        ["Layer.Filter"] = "Show annotations from",
        ["Layer.Filter.AllVisible"] = "All visible layers",
        ["Layer.Add"] = "New layer",
        ["Layer.DefaultName"] = "Key arguments",
        ["Layer.DefaultNameFormat"] = "Layer {0}",
        ["Layer.Visible"] = "Layer visible",
        ["Layer.Hidden"] = "Layer hidden",
        ["Layer.Merge"] = "Merge layer",
        ["Layer.Delete"] = "Delete layer",
        ["Layer.Renamed"] = "Layer renamed",
        ["Layer.Deleted"] = "Layer deleted",
        ["Layer.Merged"] = "Layer merged",
        ["Layer.AtLeastOne"] = "At least one layer is required",
        ["Citation.Capture"] = "Capture citation",
        ["Citation.Copy"] = "Copy citation",
        ["Citation.Export"] = "Export citation",
        ["Citation.Copied"] = "Citation copied to clipboard",
        ["Citation.Exported"] = "Citation exported",
        ["Citation.NoSelection"] = "Select text before capturing a citation",
        ["Citation.PageFormat"] = "p.{0}",
        ["Citation.UnknownTitle"] = "Unknown title",
        ["Citation.UnknownAuthor"] = "Unknown author",
        ["ReadingMemory.Open"] = "Reading memory",
        ["ReadingMemory.Disposition"] = "Disposition",
        ["ReadingMemory.OpenedBecause"] = "Why I opened this",
        ["ReadingMemory.KeyInsight"] = "Key insight",
        ["ReadingMemory.OpenQuestions"] = "Open questions",
        ["ReadingMemory.Saved"] = "Reading memory saved",
        ["ReadingMemory.Save"] = "Save memory",
        ["ReadingMemory.InvalidDisposition"] = "Disposition must be a number from 1 to 5",

        ["Icon.ic_annotation_highlight.Label"] = "Highlight",
        ["Icon.ic_annotation_highlight_color.Label"] = "Choose highlight color",
        ["Icon.ic_annotation_note.Label"] = "Add note",
        ["Icon.ic_annotation_note_anchor.Label"] = "Note",
        ["Icon.ic_annotation_delete.Label"] = "Delete annotation",
        ["Icon.ic_annotation_panel.Label"] = "Annotations",
        ["Icon.ic_bookmark_add.Label"] = "Add bookmark",
        ["Icon.ic_bookmark_remove.Label"] = "Remove bookmark",
        ["Icon.ic_bookmark_panel.Label"] = "Bookmarks",
        ["Icon.ic_bookmark_item.Label"] = "Bookmark",
        ["Icon.ic_bookmark_rename.Label"] = "Rename bookmark",
        ["Icon.ic_layer_panel.Label"] = "Annotation layers",
        ["Icon.ic_layer_add.Label"] = "New layer",
        ["Icon.ic_layer_visible.Label"] = "Layer visible",
        ["Icon.ic_layer_hidden.Label"] = "Layer hidden",
        ["Icon.ic_layer_merge.Label"] = "Merge layer",
        ["Icon.ic_layer_delete.Label"] = "Delete layer",
        ["Icon.ic_citation_capture.Label"] = "Capture citation",
        ["Icon.ic_citation_copy.Label"] = "Copy citation",
        ["Icon.ic_citation_export.Label"] = "Export citation",
        ["Icon.ic_reading_memory.Label"] = "Reading memory",
        ["Icon.ic_reading_memory_disposition.Label"] = "Disposition",

        ["Icon.ic_grid_view.Label"] = "Grid view",
        ["Icon.ic_list_view.Label"] = "List view",
        ["Icon.ic_directory_view.Label"] = "Directory view",
        ["Icon.ic_3d_view.Label"] = "3D shelf view (coming in Phase 14)",
        ["Icon.ic_filter.Label"] = "Filter",
        ["Icon.ic_filter_clear.Label"] = "Clear filters",
        ["Icon.ic_sort_asc.Label"] = "Sort ascending",
        ["Icon.ic_sort_desc.Label"] = "Sort descending",
        ["Icon.ic_shelf.Label"] = "Shelf",
        ["Icon.ic_shelf_smart.Label"] = "Smart shelf",
        ["Icon.ic_shelf_add.Label"] = "Add shelf",
        ["Icon.ic_shelf_rename.Label"] = "Rename shelf",
        ["Icon.ic_shelf_delete.Label"] = "Delete shelf",
        ["Icon.ic_shelf_drag.Label"] = "Drag to reorder",
        ["Icon.ic_tag.Label"] = "Tag",
        ["Icon.ic_tag_add.Label"] = "Add tag",
        ["Icon.ic_tag_remove.Label"] = "Remove tag",
        ["Icon.ic_open_reader.Label"] = "Open reader",
        ["Icon.ic_enrich.Label"] = "Enrich metadata",
        ["Icon.ic_book_no_cover.Label"] = "No cover available",
        ["Icon.ic_provenance.Label"] = "Provenance",
        ["Icon.ic_edit_inline.Label"] = "Edit",
        ["Icon.ic_field_group_file.Label"] = "File information",
        ["Icon.ic_field_group_biblio.Label"] = "Bibliographic information",
        ["Icon.ic_field_group_reading.Label"] = "Reading information",
        ["Icon.ic_field_group_enrichment.Label"] = "Enrichment information",
        ["Icon.ic_field_group_ai.Label"] = "AI information",
        ["Icon.ic_bulk_edit.Label"] = "Bulk edit",
        ["Icon.ic_bulk_select_all.Label"] = "Select all",
        ["Icon.ic_bulk_deselect.Label"] = "Deselect all",
        ["Icon.ic_undo.Label"] = "Undo",
        ["Icon.ic_preview.Label"] = "Preview",
        ["Icon.ic_empty_library.Label"] = "Empty library",
        ["Icon.ic_empty_filter.Label"] = "No results",
        ["Icon.ic_empty_shelf.Label"] = "Empty shelf",
        ["Icon.ic_folder.Label"] = "Folder",
        ["Icon.ic_close_panel.Label"] = "Close panel",
    };

    private static readonly IReadOnlyDictionary<string, string> French = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["MainWindow.Title"] = "Bibliothèque Ogma",
        ["MainWindow.Tagline"] = "Votre bibliothèque PDF personnelle — élégamment gérée, intelligemment conseillée.",
        ["MainWindow.EmptyState.Heading"] = "Votre bibliothèque apparaîtra ici",
        ["MainWindow.EmptyState.Body"] = "Choisissez un dossier de PDF pour commencer. Ogma l'analysera, reconnaîtra vos livres et vous laissera les parcourir sous forme de couvertures et de tranches.",
        ["MainWindow.Action.ChooseFolder"] = "Choisir le dossier de la bibliothèque",
        ["MainWindow.Action.OpenPdf"] = "Ouvrir un PDF",
        ["MainWindow.Status.Skeleton"] = "Version squelette — Phase 02",

        // Phase 03 icon accessible labels (fr)
        ["Icon.ic_app_logo.Label"] = "Bibliothèque Ogma",
        ["Icon.ic_settings.Label"] = "Paramètres",
        ["Icon.ic_keyboard_shortcut.Label"] = "Raccourci clavier",
        ["Icon.ic_close.Label"] = "Fermer",
        ["Icon.ic_search.Label"] = "Rechercher",
        ["Icon.ic_lib_scan.Label"] = "Scanner la bibliothèque",
        ["Icon.ic_lib_folder_open.Label"] = "Ouvrir le dossier",
        ["Icon.ic_lib_health.Label"] = "Santé de la bibliothèque",
        ["Icon.ic_lib_preferences.Label"] = "Préférences de bibliothèque",
        ["Icon.ic_cat_view_grid.Label"] = "Vue grille",
        ["Icon.ic_cat_view_list.Label"] = "Vue liste",
        ["Icon.ic_cat_view_shelf3d.Label"] = "Vue étagère 3D",
        ["Icon.ic_cat_view_directory.Label"] = "Vue répertoire",
        ["Icon.ic_cat_shelf.Label"] = "Étagère",
        ["Icon.ic_cat_shelf_new.Label"] = "Nouvelle étagère",
        ["Icon.ic_cat_filter.Label"] = "Filtrer",
        ["Icon.ic_cat_sort.Label"] = "Trier",
        ["Icon.ic_read_open.Label"] = "Ouvrir le livre",
        ["Icon.ic_read_bookmark.Label"] = "Signet",
        ["Icon.ic_read_zoom_in.Label"] = "Zoom avant",
        ["Icon.ic_read_zoom_out.Label"] = "Zoom arrière",
        ["Icon.ic_read_fullscreen.Label"] = "Plein écran",
        ["Icon.ic_search_metadata.Label"] = "Rechercher des livres",
        ["Icon.ic_search_fulltext.Label"] = "Recherche plein texte",
        ["Icon.ic_ai_advisor.Label"] = "Conseiller IA",
        ["Icon.ic_ai_privacy.Label"] = "Confidentialité IA",
        ["Icon.ic_ai_disable.Label"] = "Désactiver l'IA",
        ["Icon.ic_set_appearance.Label"] = "Apparence",
        ["Icon.ic_set_language.Label"] = "Langue",
        ["Icon.ic_set_updates.Label"] = "Mises à jour",
        ["Icon.ic_set_about.Label"] = "À propos",
        ["Icon.ic_status_available.Label"] = "Disponible",
        ["Icon.ic_status_unavailable.Label"] = "Indisponible",
        ["Icon.ic_status_loading.Label"] = "Chargement",

        // Phase 05 — Scan progress and status strings (fr)
        ["Scan.Phase.Idle"] = "Prêt",
        ["Scan.Phase.Discovering"] = "Découverte des fichiers…",
        ["Scan.Phase.Processing"] = "Traitement…",
        ["Scan.Phase.GeneratingAssets"] = "Génération des miniatures…",
        ["Scan.Phase.Complete"] = "Analyse terminée",
        ["Scan.Phase.PartialFailure"] = "Analyse terminée — certains fichiers ont échoué",
        ["Scan.Phase.Cancelled"] = "Analyse annulée",
        ["Scan.Status.Scanned"] = "{0} livres analysés",
        ["Scan.Button.Cancel"] = "Annuler",
        ["Scan.Progress.Files"] = "{0} / {1} fichiers",
        ["Scan.Progress.Failed"] = "{0} échoués",
        ["MainWindow.FolderPicker.Opening"] = "Ouverture du selecteur de dossier...",
        ["MainWindow.FolderPicker.ScanStarting"] = "Dossier de bibliotheque choisi. Analyse en cours...",
        ["MainWindow.FolderPicker.Unavailable"] = "Le selecteur de dossier n'est pas disponible dans cette fenetre.",
        ["MainWindow.FolderPicker.NotConfigured"] = "Le selecteur de dossier de bibliotheque n'est pas configure.",
        ["MainWindow.FolderPicker.FailedFormat"] = "Echec du selecteur de dossier : {0}",
        ["MainWindow.PdfPicker.Opening"] = "Ouverture du selecteur PDF...",
        ["MainWindow.PdfPicker.Registering"] = "Enregistrement du PDF choisi...",
        ["MainWindow.PdfPicker.Opened"] = "PDF ouvert dans le lecteur.",
        ["MainWindow.PdfPicker.Unavailable"] = "Le selecteur PDF n'est pas disponible dans cette fenetre.",
        ["MainWindow.PdfPicker.NotConfigured"] = "L'ouverture directe de PDF n'est pas configuree.",
        ["MainWindow.PdfPicker.FailedFormat"] = "Echec de l'ouverture PDF : {0}",
        ["MainWindow.PdfPicker.PdfFiles"] = "Documents PDF",
        ["MainWindow.Status.Ready"] = "Prêt — choisissez un dossier de bibliothèque pour commencer",

        // Phase 06 — Catalogue browsing strings (fr)
        ["Catalogue.ViewToggle.Grid"] = "Vue en grille",
        ["Catalogue.ViewToggle.List"] = "Vue en liste",
        ["Catalogue.ViewToggle.Directory"] = "Vue répertoire",
        ["Catalogue.ViewToggle.Shelf3D"] = "Étagère 3D (à venir dans la phase 14)",
        ["Catalogue.Filter.ClearAll"] = "Effacer tous les filtres",
        ["Catalogue.Filter.Title"] = "Filtrer par titre",
        ["Catalogue.Filter.Author"] = "Filtrer par auteur",
        ["Catalogue.Filter.Status"] = "Filtrer par statut",
        ["Catalogue.Filter.Rating"] = "Filtrer par note",
        ["Catalogue.Filter.Availability"] = "Filtrer par disponibilité",
        ["Catalogue.Sort.Title"] = "Trier par titre",
        ["Catalogue.Sort.Author"] = "Trier par auteur",
        ["Catalogue.Sort.Year"] = "Trier par année",
        ["Catalogue.Sort.Rating"] = "Trier par note",
        ["Catalogue.Sort.Status"] = "Trier par statut",
        ["Catalogue.Sort.Ascending"] = "Croissant",
        ["Catalogue.Sort.Descending"] = "Décroissant",
        ["Catalogue.Shelf.New"] = "Nouvelle étagère",
        ["Catalogue.Shelf.Rename"] = "Renommer l'étagère",
        ["Catalogue.Shelf.Delete"] = "Supprimer l'étagère",
        ["Catalogue.BookDetail.Read"] = "Lire",
        ["Catalogue.BookDetail.Enrich"] = "Enrichir",
        ["Catalogue.BookDetail.Close"] = "Fermer",
        ["Catalogue.BookDetail.EnrichTooltip"] = "Rechercher les metadonnees dans Google Books et Open Library",
        ["Catalogue.BookDetail.Enriching"] = "Recherche des metadonnees du livre...",
        ["Catalogue.BookDetail.EnrichComplete"] = "Enrichissement des metadonnees termine.",
        ["Catalogue.BookDetail.EnrichUnavailable"] = "L'enrichissement des metadonnees est indisponible.",
        ["Catalogue.BookDetail.EnrichUnknownError"] = "Erreur inconnue",
        ["Catalogue.BookDetail.EnrichFailedFormat"] = "Echec de l'enrichissement des metadonnees : {0}",
        ["Catalogue.BookDetail.ReadingMemory"] = "Mémoire de lecture",
        ["Catalogue.BookDetail.ReadingMemoryKeyInsight"] = "Insight clé",
        ["Catalogue.BookDetail.ReadingMemoryDisposition"] = "Appréciation",
        ["Catalogue.BookDetail.ReadingMemoryDispositionFormat"] = "{0}/5",
        ["Catalogue.BookDetail.ReadingMemoryEmpty"] = "Non renseigné",
        ["Catalogue.Empty.NoResults"] = "Aucun livre ne correspond aux filtres actuels",
        ["Catalogue.Empty.NoShelfBooks"] = "Cette étagère ne contient pas encore de livres",
        ["Reader.Phase08Placeholder"] = "Lecteur PDF à venir dans la Phase 08",

        // Phase 08 — Reader strings (fr)
        ["Reader.Navigation.FirstPage"] = "Première page",
        ["Reader.Navigation.PreviousPage"] = "Page précédente",
        ["Reader.Navigation.NextPage"] = "Page suivante",
        ["Reader.Navigation.LastPage"] = "Dernière page",
        ["Reader.Navigation.GoBack"] = "Retour",
        ["Reader.Navigation.GoForward"] = "Avancer",
        ["Reader.Navigation.JumpToPage"] = "Aller à la page",
        ["Reader.Navigation.PageOf"] = "Page {0} sur {1}",
        ["Reader.Navigation.InvalidPage"] = "La page doit être entre 1 et {0}",
        ["Reader.Zoom.FitWidth"] = "Ajuster la largeur",
        ["Reader.Zoom.FitPage"] = "Ajuster la page",
        ["Reader.Zoom.Fixed"] = "{0}%",
        ["Reader.Zoom.ZoomIn"] = "Zoom avant",
        ["Reader.Zoom.ZoomOut"] = "Zoom arrière",
        ["Reader.Display.SinglePage"] = "Page unique",
        ["Reader.Display.TwoPage"] = "Deux pages",
        ["Reader.Display.Continuous"] = "Défilement continu",
        ["Reader.FullScreen.Enter"] = "Plein écran",
        ["Reader.FullScreen.Exit"] = "Quitter le plein écran",
        ["Reader.Search.Placeholder"] = "Rechercher dans le document…",
        ["Reader.Search.NoResults"] = "Aucun résultat trouvé",
        ["Reader.Search.MatchCount"] = "{0} résultat(s)",
        ["Reader.Search.NoTextLayer"] = "Pas de couche texte — ROC disponible dans V1",
        ["Reader.Error.FileNotFound"] = "Le fichier PDF est introuvable.",
        ["Reader.Error.RenderFailed"] = "La page n'a pas pu être rendue.",
        ["Reader.Panel.Title"] = "Lecteur",

        // Phase 09 — Annotations, Bookmarks & Reading Memory (fr)
        ["Annotation.Highlight.Create"] = "Surligner",
        ["Annotation.Highlight.Color"] = "Choisir la couleur de surlignage",
        ["Annotation.Highlight.LayerColor"] = "Couleur de la couche",
        ["Annotation.Note.Create"] = "Ajouter une note",
        ["Annotation.Note.Anchor"] = "Note",
        ["Annotation.Note.Edit"] = "Modifier la note",
        ["Annotation.Note.Editor"] = "Note",
        ["Annotation.Note.Saved"] = "Note enregistrée",
        ["Annotation.Delete"] = "Supprimer l'annotation",
        ["Annotation.Panel"] = "Annotations",
        ["Annotation.Saved"] = "Annotation enregistrée",
        ["Annotation.Deleted"] = "Annotation supprimée",
        ["Annotation.SelectionQuoteFormat"] = "Sélection à la page {0}",
        ["Annotation.SampleQuoteFormat"] = "Surlignage à la page {0}",
        ["Annotation.SampleNoteFormat"] = "Note à la page {0}",
        ["Annotation.AccessibleLabelWithLayerFormat"] = "{0} - {1} - {2}",
        ["Annotation.AccessibleLabelWithoutLayerFormat"] = "{0} - {1}",
        ["Annotation.Delete.Confirm"] = "Supprimer",
        ["Annotation.Delete.Cancel"] = "Annuler",
        ["Annotation.Delete.Confirmation"] = "Supprimer cette annotation ({0}) ?",
        ["Bookmark.Add"] = "Ajouter un signet",
        ["Bookmark.Remove"] = "Supprimer le signet",
        ["Bookmark.Panel"] = "Signets",
        ["Bookmark.Item"] = "Signet",
        ["Bookmark.Rename"] = "Renommer le signet",
        ["Bookmark.Renamed"] = "Signet renommé",
        ["Bookmark.Saved"] = "Signet enregistré",
        ["Bookmark.Removed"] = "Signet supprimé",
        ["Bookmark.DefaultLabelFormat"] = "Page {0}",
        ["Bookmark.Panel.AccessibleFormat"] = "{0} ({1})",
        ["Layer.Panel"] = "Couches d'annotation",
        ["Layer.Filter"] = "Afficher les annotations de",
        ["Layer.Filter.AllVisible"] = "Toutes les couches visibles",
        ["Layer.Add"] = "Nouvelle couche",
        ["Layer.DefaultName"] = "Arguments clés",
        ["Layer.DefaultNameFormat"] = "Couche {0}",
        ["Layer.Visible"] = "Couche visible",
        ["Layer.Hidden"] = "Couche masquée",
        ["Layer.Merge"] = "Fusionner la couche",
        ["Layer.Delete"] = "Supprimer la couche",
        ["Layer.Renamed"] = "Couche renommée",
        ["Layer.Deleted"] = "Couche supprimée",
        ["Layer.Merged"] = "Couches fusionnees",
        ["Layer.AtLeastOne"] = "Au moins une couche est requise",
        ["Citation.Capture"] = "Capturer la citation",
        ["Citation.Copy"] = "Copier la citation",
        ["Citation.Export"] = "Exporter la citation",
        ["Citation.Copied"] = "Citation copiée dans le presse-papiers",
        ["Citation.Exported"] = "Citation exportée",
        ["Citation.NoSelection"] = "Sélectionnez du texte avant de capturer une citation",
        ["Citation.PageFormat"] = "p. {0}",
        ["Citation.UnknownTitle"] = "Titre inconnu",
        ["Citation.UnknownAuthor"] = "Auteur inconnu",
        ["ReadingMemory.Open"] = "Mémoire de lecture",
        ["ReadingMemory.Disposition"] = "Appréciation",
        ["ReadingMemory.OpenedBecause"] = "Pourquoi j'ai ouvert ce livre",
        ["ReadingMemory.KeyInsight"] = "Insight clé",
        ["ReadingMemory.OpenQuestions"] = "Questions ouvertes",
        ["ReadingMemory.Saved"] = "Mémoire de lecture enregistrée",
        ["ReadingMemory.Save"] = "Enregistrer la mémoire",
        ["ReadingMemory.InvalidDisposition"] = "L'appréciation doit être un nombre de 1 à 5",

        ["Icon.ic_annotation_highlight.Label"] = "Surligner",
        ["Icon.ic_annotation_highlight_color.Label"] = "Choisir la couleur de surlignage",
        ["Icon.ic_annotation_note.Label"] = "Ajouter une note",
        ["Icon.ic_annotation_note_anchor.Label"] = "Note",
        ["Icon.ic_annotation_delete.Label"] = "Supprimer l'annotation",
        ["Icon.ic_annotation_panel.Label"] = "Annotations",
        ["Icon.ic_bookmark_add.Label"] = "Ajouter un signet",
        ["Icon.ic_bookmark_remove.Label"] = "Supprimer le signet",
        ["Icon.ic_bookmark_panel.Label"] = "Signets",
        ["Icon.ic_bookmark_item.Label"] = "Signet",
        ["Icon.ic_bookmark_rename.Label"] = "Renommer le signet",
        ["Icon.ic_layer_panel.Label"] = "Couches d'annotation",
        ["Icon.ic_layer_add.Label"] = "Nouvelle couche",
        ["Icon.ic_layer_visible.Label"] = "Couche visible",
        ["Icon.ic_layer_hidden.Label"] = "Couche masquée",
        ["Icon.ic_layer_merge.Label"] = "Fusionner la couche",
        ["Icon.ic_layer_delete.Label"] = "Supprimer la couche",
        ["Icon.ic_citation_capture.Label"] = "Capturer la citation",
        ["Icon.ic_citation_copy.Label"] = "Copier la citation",
        ["Icon.ic_citation_export.Label"] = "Exporter la citation",
        ["Icon.ic_reading_memory.Label"] = "Mémoire de lecture",
        ["Icon.ic_reading_memory_disposition.Label"] = "Appréciation",

        ["Icon.ic_grid_view.Label"] = "Vue en grille",
        ["Icon.ic_list_view.Label"] = "Vue en liste",
        ["Icon.ic_directory_view.Label"] = "Vue répertoire",
        ["Icon.ic_3d_view.Label"] = "Vue étagère 3D (à venir dans la Phase 14)",
        ["Icon.ic_filter.Label"] = "Filtrer",
        ["Icon.ic_filter_clear.Label"] = "Effacer les filtres",
        ["Icon.ic_sort_asc.Label"] = "Tri croissant",
        ["Icon.ic_sort_desc.Label"] = "Tri décroissant",
        ["Icon.ic_shelf.Label"] = "Étagère",
        ["Icon.ic_shelf_smart.Label"] = "Étagère intelligente",
        ["Icon.ic_shelf_add.Label"] = "Ajouter une étagère",
        ["Icon.ic_shelf_rename.Label"] = "Renommer l'étagère",
        ["Icon.ic_shelf_delete.Label"] = "Supprimer l'étagère",
        ["Icon.ic_shelf_drag.Label"] = "Glisser pour réorganiser",
        ["Icon.ic_tag.Label"] = "Étiquette",
        ["Icon.ic_tag_add.Label"] = "Ajouter une étiquette",
        ["Icon.ic_tag_remove.Label"] = "Retirer l'étiquette",
        ["Icon.ic_open_reader.Label"] = "Ouvrir le lecteur",
        ["Icon.ic_enrich.Label"] = "Enrichir les métadonnées",
        ["Icon.ic_book_no_cover.Label"] = "Pas de couverture disponible",
        ["Icon.ic_provenance.Label"] = "Provenance",
        ["Icon.ic_edit_inline.Label"] = "Modifier",
        ["Icon.ic_field_group_file.Label"] = "Informations de fichier",
        ["Icon.ic_field_group_biblio.Label"] = "Informations bibliographiques",
        ["Icon.ic_field_group_reading.Label"] = "Informations de lecture",
        ["Icon.ic_field_group_enrichment.Label"] = "Informations d'enrichissement",
        ["Icon.ic_field_group_ai.Label"] = "Informations IA",
        ["Icon.ic_bulk_edit.Label"] = "Modification groupée",
        ["Icon.ic_bulk_select_all.Label"] = "Tout sélectionner",
        ["Icon.ic_bulk_deselect.Label"] = "Tout désélectionner",
        ["Icon.ic_undo.Label"] = "Annuler",
        ["Icon.ic_preview.Label"] = "Aperçu",
        ["Icon.ic_empty_library.Label"] = "Bibliothèque vide",
        ["Icon.ic_empty_filter.Label"] = "Aucun résultat",
        ["Icon.ic_empty_shelf.Label"] = "Étagère vide",
        ["Icon.ic_folder.Label"] = "Dossier",
        ["Icon.ic_close_panel.Label"] = "Fermer le panneau",
    };

    private IReadOnlyDictionary<string, string> _active = English;

    /// <inheritdoc />
    public CultureInfo CurrentCulture { get; private set; } = CultureInfo.GetCultureInfo("en");

    /// <inheritdoc />
    public event EventHandler? CultureChanged;

    /// <inheritdoc />
    public string this[string key]
    {
        get
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(key);
            return _active.TryGetValue(key, out string? value) ? value : $"⟦{key}⟧";
        }
    }

    /// <inheritdoc />
    public void SetCulture(string cultureName)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(cultureName);
        string twoLetter = CultureInfo.GetCultureInfo(cultureName).TwoLetterISOLanguageName;
        _active = twoLetter == "fr" ? French : English;
        CurrentCulture = CultureInfo.GetCultureInfo(twoLetter);
        CultureChanged?.Invoke(this, EventArgs.Empty);
    }
}
