using OgmaLibrary.Application.Catalogue;
using OgmaLibrary.Application.Ingestion;
using OgmaLibrary.Infrastructure.Pdf;

namespace OgmaLibrary.Infrastructure.Assets;

/// <summary>
/// Renders page 0 of a PDF at low resolution, scales to a 7×100 spine strip,
/// and writes a JPEG to the sidecar (FR-LIB-005, used by 3D shelf in Phase 14).
/// Always runs off the UI thread via <c>Task.Run</c>.
/// </summary>
public sealed class SpineService : ISpineService
{
    private readonly ISidecarService _sidecar;
    private readonly PdfWorkerClient _workerClient;
    private readonly IVisualAssetService? _visualAssets;

    /// <summary>
    /// Initializes a new instance of <see cref="SpineService"/>.
    /// </summary>
    /// <param name="sidecar">The sidecar service used to resolve output paths.</param>
    public SpineService(ISidecarService sidecar)
        : this(sidecar, new PdfWorkerClient(), null)
    {
    }

    /// <summary>
    /// Initializes a new instance of <see cref="SpineService"/>.
    /// </summary>
    /// <param name="sidecar">The sidecar service used to resolve output paths.</param>
    /// <param name="workerClient">The isolated PDF worker client.</param>
    public SpineService(ISidecarService sidecar, PdfWorkerClient workerClient)
        : this(sidecar, workerClient, null)
    {
    }

    /// <summary>Initializes the generator with durable manifest registration.</summary>
    public SpineService(
        ISidecarService sidecar,
        PdfWorkerClient workerClient,
        IVisualAssetService? visualAssets)
    {
        ArgumentNullException.ThrowIfNull(sidecar);
        ArgumentNullException.ThrowIfNull(workerClient);
        _sidecar = sidecar;
        _workerClient = workerClient;
        _visualAssets = visualAssets;
    }

    /// <inheritdoc />
    public async Task<(bool Success, string? ErrorMessage)> GenerateSpineAsync(
        string bookId,
        string contentHash,
        string absoluteFilePath,
        CancellationToken cancellationToken = default)
    {
        return await GenerateSpineVariantAsync(
            bookId,
            contentHash,
            absoluteFilePath,
            VisualAssetVariants.SpineDefault.Name,
            cancellationToken).ConfigureAwait(false);
    }

    /// <inheritdoc />
    public async Task<(bool Success, string? ErrorMessage)> GenerateSpineVariantAsync(
        string bookId,
        string contentHash,
        string absoluteFilePath,
        string variant,
        CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(bookId);
        ArgumentException.ThrowIfNullOrWhiteSpace(contentHash);
        ArgumentException.ThrowIfNullOrWhiteSpace(absoluteFilePath);
        VisualAssetVariantDefinition definition =
            VisualAssetVariants.Resolve(VisualAssetKind.Spine, variant);

        try
        {
            string? suffix = definition.Name == VisualAssetVariants.SpineDefault.Name
                ? null
                : $"_{definition.Name}";
            string outputPath = _sidecar.Resolve(contentHash, SidecarClass.Spines, suffix);

            await Task.Run(
                () => _workerClient.GenerateSpine(
                    absoluteFilePath, outputPath, definition.WidthPx, definition.HeightPx),
                cancellationToken).ConfigureAwait(false);

            if (_visualAssets is not null)
            {
                await _visualAssets.RegisterGeneratedAsync(
                    bookId,
                    contentHash,
                    VisualAssetKind.Spine,
                    definition.Name,
                    _sidecar.ResolveRelative(contentHash, SidecarClass.Spines, suffix),
                    definition.WidthPx,
                    definition.HeightPx,
                    "jpg",
                    generationVersion: 1,
                    cancellationToken: cancellationToken).ConfigureAwait(false);
            }

            return (true, null);
        }
        catch (Exception ex) when (ex is not OperationCanceledException)
        {
            return (false, "Spine generation failed.");
        }
    }

    /// <summary>Spine width generated by the isolated worker.</summary>
    public static int GeneratedSpineWidth => VisualAssetVariants.SpineDefault.WidthPx;

    /// <summary>Spine height generated by the isolated worker.</summary>
    public static int GeneratedSpineHeight => VisualAssetVariants.SpineDefault.HeightPx;
}
