using OgmaLibrary.Application.Catalogue;
using OgmaLibrary.Application.Ingestion;
using OgmaLibrary.Infrastructure.Pdf;

namespace OgmaLibrary.Infrastructure.Assets;

/// <summary>
/// Renders page 0 of a PDF at low resolution, scales to a 7×100 spine strip,
/// and writes a JPEG to the sidecar (FR-LIB-005, used by 3D shelf in Phase 14).
/// Always runs off the UI thread via <c>Task.Run</c>.
/// </summary>
public sealed class SpineService : ISpineService
{
    private const int SpineWidth = 7;
    private const int SpineHeight = 100;

    private readonly ISidecarService _sidecar;
    private readonly PdfWorkerClient _workerClient;

    /// <summary>
    /// Initializes a new instance of <see cref="SpineService"/>.
    /// </summary>
    /// <param name="sidecar">The sidecar service used to resolve output paths.</param>
    public SpineService(ISidecarService sidecar)
        : this(sidecar, new PdfWorkerClient())
    {
    }

    /// <summary>
    /// Initializes a new instance of <see cref="SpineService"/>.
    /// </summary>
    /// <param name="sidecar">The sidecar service used to resolve output paths.</param>
    /// <param name="workerClient">The isolated PDF worker client.</param>
    public SpineService(ISidecarService sidecar, PdfWorkerClient workerClient)
    {
        ArgumentNullException.ThrowIfNull(sidecar);
        ArgumentNullException.ThrowIfNull(workerClient);
        _sidecar = sidecar;
        _workerClient = workerClient;
    }

    /// <inheritdoc />
    public async Task<(bool Success, string? ErrorMessage)> GenerateSpineAsync(
        string bookId,
        string contentHash,
        string absoluteFilePath,
        CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(bookId);
        ArgumentException.ThrowIfNullOrWhiteSpace(contentHash);
        ArgumentException.ThrowIfNullOrWhiteSpace(absoluteFilePath);

        try
        {
            string outputPath = _sidecar.Resolve(contentHash, SidecarClass.Spines);

            await Task.Run(() =>
            {
                _workerClient.GenerateSpine(absoluteFilePath, outputPath);
            }, cancellationToken).ConfigureAwait(false);

            return (true, null);
        }
        catch (Exception ex) when (ex is not OperationCanceledException)
        {
            return (false, ex.Message);
        }
    }

    /// <summary>Spine width generated by the isolated worker.</summary>
    public static int GeneratedSpineWidth => SpineWidth;

    /// <summary>Spine height generated by the isolated worker.</summary>
    public static int GeneratedSpineHeight => SpineHeight;
}
