using OgmaLibrary.Application.Catalogue;
using OgmaLibrary.Application.Ingestion;
using OgmaLibrary.Infrastructure.Pdf;

namespace OgmaLibrary.Infrastructure.Assets;

/// <summary>
/// Renders page 0 of a PDF with PDFtoImage (spike S02 winner, v5.x for SkiaSharp 3.x),
/// resizes to 200×300 px via SkiaSharp, and writes a JPEG 85% to the sidecar
/// (FR-LIB-005). Always runs off the UI thread via <c>Task.Run</c>.
/// </summary>
public sealed class ThumbnailService : IThumbnailService
{
    private const int TargetWidth = 200;
    private const int TargetHeight = 300;

    private readonly ISidecarService _sidecar;
    private readonly PdfWorkerClient _workerClient;

    /// <summary>
    /// Initializes a new instance of <see cref="ThumbnailService"/>.
    /// </summary>
    /// <param name="sidecar">The sidecar service used to resolve output paths.</param>
    public ThumbnailService(ISidecarService sidecar)
        : this(sidecar, new PdfWorkerClient())
    {
    }

    /// <summary>
    /// Initializes a new instance of <see cref="ThumbnailService"/>.
    /// </summary>
    /// <param name="sidecar">The sidecar service used to resolve output paths.</param>
    /// <param name="workerClient">The isolated PDF worker client.</param>
    public ThumbnailService(ISidecarService sidecar, PdfWorkerClient workerClient)
    {
        ArgumentNullException.ThrowIfNull(sidecar);
        ArgumentNullException.ThrowIfNull(workerClient);
        _sidecar = sidecar;
        _workerClient = workerClient;
    }

    /// <inheritdoc />
    public async Task<(bool Success, string? ErrorMessage)> GenerateCoverAsync(
        string bookId,
        string contentHash,
        string absoluteFilePath,
        CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(bookId);
        ArgumentException.ThrowIfNullOrWhiteSpace(contentHash);
        ArgumentException.ThrowIfNullOrWhiteSpace(absoluteFilePath);

        try
        {
            string outputPath = _sidecar.Resolve(contentHash, SidecarClass.Covers);

            await Task.Run(() =>
            {
                _workerClient.GenerateCover(absoluteFilePath, outputPath);
            }, cancellationToken).ConfigureAwait(false);

            return (true, null);
        }
        catch (Exception ex) when (ex is not OperationCanceledException)
        {
            return (false, ex.Message);
        }
    }

    /// <summary>Cover width generated by the isolated worker.</summary>
    public static int GeneratedCoverWidth => TargetWidth;

    /// <summary>Cover height generated by the isolated worker.</summary>
    public static int GeneratedCoverHeight => TargetHeight;
}
