<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaVersion>11.3.17</AvaloniaVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OgmaLibrary.Domain\OgmaLibrary.Domain.csproj" />
    <ProjectReference Include="..\OgmaLibrary.Application\OgmaLibrary.Application.csproj" />
    <ProjectReference Include="..\OgmaLibrary.Infrastructure\OgmaLibrary.Infrastructure.csproj" />
    <ProjectReference Include="..\OgmaLibrary.Reader\OgmaLibrary.Reader.csproj" />
    <ProjectReference Include="..\OgmaLibrary.Bookshelf3D\OgmaLibrary.Bookshelf3D.csproj" />
    <ProjectReference Include="..\OgmaLibrary.Workers\OgmaLibrary.Workers.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
    <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Diagnostics" Version="$(AvaloniaVersion)" Condition="'$(Configuration)' == 'Debug'" />
  </ItemGroup>

</Project>
